// <auto-generated />
namespace Find_Your_Petrol1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class third : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(third));
        
        string IMigrationMetadata.Id
        {
            get { return "202101251208369_third"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
